package com.dgtz.api.enums;

/**
 * Created with IntelliJ IDEA.
 * User: root
 * Date: 12/15/13
 * Time: 5:31 PM
 * To change this template use File | Settings | File Templates.
 */
public enum EnumErrors {

    OK(0x00),
    NO_ERRORS(0x01),
    ERROR_IN_COMPRESSING(0x02),
    ERROR_IN_IMG_CAPTURING(0x03),
    UNKNOWN_ERROR(0x04),
    MAIL_MATCH_ERR(0x05),
    MKDIR_ERR(0x06),
    PUBLISH_ERR(0x07),
    MAIL_SEND_ERR(0x08),
    RATE_ERROR(0x09),
    SOCIAL_AUTH_ERROR(0x0A),
    REPORT_ERROR(0x0B),
    CHANNEL_REMOVE_ERROR(0x0C),
    MEDIA_REMOVE_ERROR(0x0D),
    ALREADY_JOINED(0x0E),
    FILE_FORMAT_ERROR(0x0F),
    BIG_OR_SMALL_DURATION_ERROR(0x10),
    SMALL_DURATION_ERROR(0x11),
    NULL_FIELD_ERROR(0x12),
    BYTE_CONVERT_ERROR(0x13),
    NO_SUCH_MAIL(0x14),
    WAIT_FOR_JOIN(0x15),
    FORBIDDEN(0x16),
    THUMBNAIL_ERROR(0x17),
    NO_PASS_ERROR(0x18),
    EMAIL_SUBSRB_OFF_ERROR(0x19),
    INVALID_HASH(0x1A),
    EMAIL_EXISTED(0x1B),
    ACTIVATION_ERROR(0x1C),
    NO_CHANNEL_ERROR(0x1D),
    AUTH_ERROR(0x1E),
    CANNOT_FOLLOW_YOURSELF(0x1F),
    WRONG_ID_VALUE(0x20),
    WRONG_TYPE_VALUE(0x21),
    INVALID_OLD_PASSWORD(0x22),
    NO_MEDIA_FOUND(0x23),
    FILE_UPLOAD_ERROR(0x24),
    USERNAME_EXISTED(0x25),
    MOBILE_FORMAT_ERROR(0x26),
    DENIED_TO_COMMENT(0x27),
    ERROR_NO_COMMENT_REMOVED(0x28),
    ALREADY_ACTIVATED(0x29),
    URL_EXPIRED(0x2A),
    CANNOT_SUBSCRIBE_CHANNEL(0x2B),
    UNSUBSCRIBE_CHANNEL_ERROR(0x2C),
    LIVE_ENDED(0x2D),
    ALREADEY_FOLLOWED(0x2E),
    PENDING(0x2F),
    WRONG_PASS_EMAIL(0x30),
    USER_BLOCKED(0x31),
    TOO_MANY_REQUESTS(0x32),
    WRONG_DURATION(0x33),
    ALREADY_ASSOCIATED(0x34);

    public int value;

    EnumErrors(int value) {
        this.value = value;
    }
}
